export const DEMO_DATA_ENABLED = import.meta.env.DEV || import.meta.env.VITE_ENABLE_DEMO_SEED === 'true'

export const DEMO_BOOKS = [
  {
    id: 1,
    title: 'Arabic for Beginners',
    author: 'Salma Hassan',
    sellingPrice: 120,
    costPrice: 70,
    stock: 32,
    barcode: '978001',
    isArriving: false,
  },
  {
    id: 2,
    title: 'Math Sparks 1',
    author: 'Omar Nasser',
    sellingPrice: 95,
    costPrice: 55,
    stock: 24,
    barcode: '978002',
    isArriving: false,
  },
  {
    id: 3,
    title: 'Science Lab Notes',
    author: 'Dina Fathy',
    sellingPrice: 150,
    costPrice: 85,
    stock: 18,
    barcode: '978003',
    isArriving: true,
  },
  {
    id: 4,
    title: 'English Reader Level 2',
    author: 'Layla Sadek',
    sellingPrice: 110,
    costPrice: 60,
    stock: 28,
    barcode: '978004',
    isArriving: false,
  },
  {
    id: 5,
    title: 'Coding for Kids',
    author: 'Kareem Adel',
    sellingPrice: 180,
    costPrice: 95,
    stock: 12,
    barcode: '978005',
    isArriving: false,
  },
]

export const DEMO_STUDENTS = [
  {
    id: 1,
    name: 'Maha El-Sayed',
    stage: 'third',
    gender: 'female',
    system: 'general',
    specialty: 'Science',
    phone: '+20 10 1234 5678',
  },
  {
    id: 2,
    name: 'Yousef Khaled',
    stage: 'second',
    gender: 'male',
    system: 'azhar',
    specialty: 'Literature',
    phone: '+20 12 2222 3344',
  },
  {
    id: 3,
    name: 'Amina Mostafa',
    stage: 'first',
    gender: 'female',
    system: 'general',
    specialty: 'Science',
    phone: '+20 11 4455 6677',
  },
]
